version: '3'

services:
  nodejs:
    build:
      dockerfile: docker/server/Dockerfile
    volumes:
      - .:/home/server/
    container_name: nodejs
    restart: always
    ports:
      - ${HOST_PORT}:${HOST_PORT}
networks:
  default:
    external:
      name: stock_network