version: '3.0'

services:
  nodejs:
    build: ./
    volumes:
      - './:/var/www/html'
    container_name: nodejs
    restart: always
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
networks:
  default:
    external:
      name: stock_network
